# Name of the workflow
name: Publish to open/closed beta

# Controls what will trigger the workflow. Change it to your needs.
on:
  push:
    branches: [ "beta" ]
  workflow_dispatch:

# A single workflow can have multiple jobs.
jobs:
  # 'A new job is defined with the name: "build_android"
  build_android:
    # Defines what operating system will be used for the actions.
    # For android, we will use Linux GitHub-Hosted Runner.
    runs-on: ubuntu-22.04

    # Defines what step should be passed for successful run
    steps:
      # Checkout to the selected branch
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      # Download and install flutter packages
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml

      - name: Build Unsigned App Bundle
        run: flutter build appbundle

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload to Play Store (Closed Beta)
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.dbrown.mtg_draft_tracker
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          mappingFile: ./build/app/outputs/mapping/release/mapping.txt
          debugSymbols: ./build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
          whatsNewDirectory: ./whatsnew
          track: alpha
          status: completed

      - name: Upload to Play Store (Closed Beta)
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.dbrown.mtg_draft_tracker
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          mappingFile: ./build/app/outputs/mapping/release/mapping.txt
          debugSymbols: ./build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
          whatsNewDirectory: ./whatsnew
          track: beta
          status: completed
