name: Publish to internal testers

on:
  push:
    branches: [ "qa" ]
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml

      - name: Build Unsigned App Bundle
        run: |
          OFFSET=40
          BUILD_NUM=$((${{ github.run_number }} + $OFFSET))
          flutter build appbundle --build-number $BUILD_NUM

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload to Play Store (Internal Testing)
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.dbrown.mtg_draft_tracker
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          mappingFile: ./build/app/outputs/mapping/release/mapping.txt
          debugSymbols: ./build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
          whatsNewDirectory: ./whatsnew
          track: internal
          status: completed

  build_ios:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Download Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v4
        with:
          bundle-id: com.dorianbrown.snapdrafter
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml

      - name: Build App IPA
        run: |
          OFFSET=40
          BUILD_NUM=$((${{ github.run_number }} + $OFFSET))
          flutter build ipa --build-number $BUILD_NUM --export-options-plist=ios/GithubActionsExportOptions.plist

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: build/ios/ipa/SnapDrafter.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
