# Name of github action
name: Publish to internal testers

on:
  push:
    branches: [ "ios_test" ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    steps:

      # Checkout this repository and branch
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
          
      - name: Download Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.dorianbrown.snapdrafter
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Build App IPA
        run: flutter build ipa --release

      - name: Debug Build Directory
        run: ls build/ios/ipa

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: build/ios/ipa/SnapDrafter.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
